---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret 
metadata:
  name: test-external-secrets-2
  namespace: test-external-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: test-external-secrets
    kind: SecretStore
  target:
    name: k8s-secret2-name
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "test-external-secrets-2"

#passes the key-value pair as defined in secrets manager