apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-nginx
  namespace: argocd
spec:
  destination:
    namespace: simple-nginx
    server: https://kubernetes.default.svc
  project:
    default
  syncPolicy:
    automated: {}
  source:
    path: APP_PATH
    repoURL: https://github.com/j-worr/cloud-examples-public
    targetRevision: main
