apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../../../base/external-secrets"

helmGlobals:
  chartHome: ../../../../../vendor-helm

helmCharts:
  - name: external-secrets
    version: 0.9.17
    namespace: external-secrets
    valuesFile: values.yaml
