---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-nginx
  name: simple-nginx
  namespace: simple-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: simple-nginx
  type: NodePort