---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: uploader
  name: uploader
  namespace: uploader
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: uploader
  type: ClusterIP