apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/argo-cd

patches:
  - path: app.simple-nginx.yaml

helmGlobals:
  chartHome: ../../../../vendor-helm

helmCharts:
  - name: argo-cd
    version: 6.7.9
    namespace: argocd
    valuesFile: ../../../base/argo-cd/base-values.yaml
    additionalValuesFiles:
      - local-values.yaml
    valuesMerge: override


#kustomize build . --enable-helm --load-restrictor LoadRestrictionsNone