apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: uploader-secret
  namespace: uploader
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: uploader
    kind: SecretStore
  target:
    name: uploader-config  
    creationPolicy: Owner
    template:
      data:
        S3_BUCKET_NAME: '{{ .bucket }}'
        QUEUE: '{{ .queue }}'
        AWS_REGION: 'us-east-1'
      engineVersion: v2
  data:
  - secretKey: bucket
    remoteRef:
      key: /dev/uploader-processor/bucket
  - secretKey: queue
    remoteRef:
      key: /dev/uploader-processor/queue

