---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret 
metadata:
  name: test-external-secrets
  namespace: test-external-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: test-external-secrets
    kind: SecretStore
  target:
    name: k8s-secret-name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data: 
        DB_SECRET: "{{ .password }}"
  data:
  - secretKey: password 
    remoteRef:
       key: "test-external-secrets"
       property: password

#above we transfrom {"password":"somepassword"} to {"DB_SECRET":"somepassword"}