name: build-apps

on:
  push:
    branches:
      - main
    paths:
      - apps/uploader-processor/processor/**
      - apps/uploader-processor/uploader/**
      - '!**/*.md'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:    
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
    
      - name: Determine changed between the previous HEAD to the current HEAD
        id: changed-files
        run: |
          echo "::set-output name=changed::$(git diff --name-only HEAD^ HEAD)"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Uploader
        if: ${{ contains(steps.changed-files.outputs.changed, 'apps/uploader-processor/uploader/') }}
        uses: docker/build-push-action@v5
        with:
          file: ./apps/uploader-processor/uploader
          push: true
          tags: uploader:latest

      - name: Build Processor
        if: ${{ contains(steps.changed-files.outputs.changed, 'apps/uploader-processor/processor/') }}
        uses: docker/build-push-action@v5
        with:
          file: ./apps/uploader-processor/processor
          push: true
          tags: processor:latest


